### ISSUE TITLE
好像不能用

### ISSUE THREAD

**Issue by jackwu365** [sundy-li/wechat_spider#1]
> C:\wechat_spider-master>go run examples\custom_output_server.go
> 2016/10/28 11:34:05 server will at port:8899
> 2016/10/28 11:42:12 [007] WARN: Error copying to client: read tcp 10.0.0.14:8899
> ->10.0.0.2:59621: read tcp 10.0.0.14:53652->217.146.190.252:443: wsarecv: An est
> ablished connection was aborted by the software in your host machine.

手机代理也设置，好像不能正常获取。。。

`

**Comment by sundy-li** [comment]
在微信上,点击任一公众号的查看历史消息, 有出现 
Running a new wechat processor, please wait... 
字样吗?

**Comment by jackwu365** [comment]
@sundy-li 啥也没有，很奇怪

**Comment by sundy-li** [comment]
我用过几个android手机亲测是可以的,  确保下服务开了, 并且 代理ip和端口 设置正确, 或者 换个手机试试

**Comment by jackwu365** [comment]
iphone 6s 测试环境，然后我用 夜神安卓模拟器也不行

**Comment by jackwu365** [comment]
物理机测试是可以的。。 魅族

**Comment by sundy-li** [comment]
抱歉, 因为模拟器虚拟机可能是 和 代理在不同的网段, 所以连接不上代理,导致不能抓取
