### ISSUE TITLE
遍历公众号所有文章失效

### ISSUE THREAD

**Issue by wlwr** [sundy-li/wechat_spider#10]
pull 最新代码，发现只能获取第一页的文章列表数据。

https://github.com/sundy-li/wechat_spider/blob/master/handler.go#L45 js 翻页无效

**Comment by sundy-li** [comment]
这个是可以配置的, 考虑大部分需求 默认不翻页
设置config结构AutoScroll字段 
https://github.com/sundy-li/wechat_spider/blob/master/spider.go#L56
