### ISSUE TITLE
请问一下翻页和批量化的问题

### ISSUE THREAD

**Issue by kangkangv5** [sundy-li/wechat_spider#12]
您好，打扰了。
请问想向下翻页时，永远显示Caused by: MsgLists not found
是什么原因？
js实现批量化是什么原理呢？

**Comment by sundy-li** [comment]
向下翻页不用手动翻页, 只需配置AutoScroll参数, 参考最新代码的simple_server.go 

js批量化,植入新的js, 浏览器定时重定向
