### ISSUE TITLE
goproxy的证书如何导入？

### ISSUE THREAD

**Issue by nvgui** [sundy-li/wechat_spider#14]
panic: Error parsing builtin CA x509: RSA key missing NULL parameters

goroutine 1 [running]:
github.com/elazarl/goproxy.init.1()
	/Users/zhang/workspace_java/wechatspider/src/github.com/elazarl/goproxy/certs.go:10 +0xf1
github.com/elazarl/goproxy.init()
	/Users/zhang/workspace_java/wechatspider/src/github.com/elazarl/goproxy/signer.go:88 +0x38e
github.com/sundy-li/wechat_spider.init()
	/Users/zhang/workspace_java/wechatspider/src/github.com/sundy-li/wechat_spider/spider.go:59 +0x85
main.init()
	/Users/zhang/workspace_java/wechatspider/src/simple_server/main/simple_server.go:16 +0x3d

**Comment by sundy-li** [comment]
自行google,  android如何导入https证书, 证书在certs目录

**Comment by nvgui** [comment]
@sundy-li 我是用mac+eclipse跑的，证书得如何导入？是导入到mac吗？

**Comment by nvgui** [comment]
@sundy-li 已经可以go1.8不行的，go1.7没有这个问题了。

**Comment by sundy-li** [comment]
恩, 暂时没有在1.8+测试过,建议用最新正式版go1.7
