### ISSUE TITLE
现在key和公众号是一一绑定的，那么现在的js批量化还能获取多个公众号的文章吗？

### ISSUE THREAD

**Issue by liudanking** [sundy-li/wechat_spider#16]
RT

**Comment by kangkangv5** [comment]
NextBiz启用后，并没有批量跑起来……什么原因……

**Comment by liudanking** [comment]
@kangkangv5  测试了一下，即使实现了NextBiz目前的代码也无法跑多个公账号。代码 https://github.com/sundy-li/wechat_spider/blob/master/handler.go#L44 只是把biz替换了，但是key值依然是上一个biz的值，所以，浏览器会提示错误。

**Comment by sundy-li** [comment]
替换biz是访问 历史文章列表页,  对应key都从客户端自动生成了, 我们测试这边是可以批量跑的,  https://github.com/sundy-li/wechat_spider/blob/master/examples/custom_output_server.go  跑这个就行了

**Comment by liudanking** [comment]
@sundy-li 

代码 https://github.com/sundy-li/wechat_spider/blob/master/handler.go#L44 我理解是插入了一段js代码，2秒后访问下一个公众号。

但是，url中的key值没出是怎样自动生成的。

我在windows上测试跑 https://github.com/sundy-li/wechat_spider/blob/master/examples/custom_output_server.go 只能跑一个公众号，调用NextBiz后，微信客户端提示错误，应该是key还是上一个公众号的key导致。是我使用的姿势不对吗？

**Comment by steven-ji** [comment]
@sundy-li 我与@liudanking碰到的问题的同样的，这个js代码没有生效，key还是上一个公众号的key，请楼主解惑下。

**Comment by sundy-li** [comment]
跑那个代码是可以批量的, 以下是我的输出 

```
➜  wechat_spider git:(master) go run examples/custom_output_server.go
2017/02/06 12:07:47 server will at port:8899
Running a new wechat processor, please wait...
result urls size => 12
Running a new wechat processor, please wait...
result urls size => 43
Running a new wechat processor, please wait...
result urls size => 79
```

你们看看有没有添加certs里面的证书

**Comment by kangkangv5** [comment]
@sundy-li 
win10添加证书以后……
 http: panic serving 127.0.0.1:58359: runtime error: invalid memory address or nil pointer dereference
goroutine 190 [running]:
net/http.(*conn).serve.func1(0xc04236cc00)
	c:/go/src/net/http/server.go:1491 +0x131
panic(0x67e820, 0xc04200c0b0)
	c:/go/src/runtime/panic.go:458 +0x251
github.com/sundy-li/wechat_spider.ProxyHandle.func1(0x0, 0xc0420d6960, 0x4c63d0)
	C:/code/GO/src/github.com/sundy-li/wechat_spider/handler.go:22 +0x7c
github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc0420ce2a0, 0x0, 0xc0420d6960, 0x0)
	C:/code/GO/src/github.com/elazarl/goproxy/actions.go:35 +0x41
github.com/elazarl/goproxy.(*ProxyConds).Do.func1(0x0, 0xc0420d6960, 0x0)
	C:/code/GO/src/github.com/elazarl/goproxy/dispatcher.go:284 +0x162
github.com/elazarl/goproxy.FuncRespHandler.Handle(0xc0420ce2c0, 0x0, 0xc0420d6960, 0x4fb845)
	C:/code/GO/src/github.com/elazarl/goproxy/actions.go:35 +0x41
github.com/elazarl/goproxy.(*ProxyHttpServer).filterResponse(0xc042078400, 0x0, 0xc0420d6960, 0x7e2f60)
	C:/code/GO/src/github.com/elazarl/goproxy/proxy.go:69 +0x9b
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc042078400, 0x7e6b60, 0xc0420425b0, 0xc0420c3860)
	C:/code/GO/src/github.com/elazarl/goproxy/proxy.go:115 +0x87e
net/http.serverHandler.ServeHTTP(0xc042078b80, 0x7e6b60, 0xc0420425b0, 0xc0420c3860)
	c:/go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc04236cc00, 0x7e7060, 0xc0421cbfc0)
	c:/go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:2293 +0x454

……

**Comment by steven-ji** [comment]
@sundy-li 在iphone中确实有安装，组织名称为：github.com/elazar/goproxy，如果没有安装，手机应该是不能连接上8899的端口的吧。

**Comment by steven-ji** [comment]
@sundy-li 又重新试了下，批量执行还是报错，服务器端报错：Caused by: MsgLists not found， 客户端报错：请在微信客户端打开链接。哪个姿势错了？

**Comment by kangkangv5** [comment]
是我使用的姿势不对么……
每次运行结果不太一样，有一两次成功了，但是需要手动按一下ctrl+c才会继续运行？？？

**Comment by sundy-li** [comment]
@steven-ji  你只需要点一下查看历史文章就行了, 不要进行其他详细文章页面点击

**Comment by sundy-li** [comment]
@kangkangv5   和control+c 无关系..  点击任意一个公众号查看历史文章按钮即可

@steven-ji  @kangkangv5  如果没有解决, 你们可以提供一下你们机器型号和微信版本,以及对应的代码(如果有修改的话)

**Comment by sundy-li** [comment]
@liudanking 你们先用android测试先, windows客户端微信最近有更新,我的代码可能不兼容

**Comment by kangkangv5** [comment]
证书装了但是尝试好多次，安卓和服务无法连接……所以才试着win端……
代码就是原生的没有改动，只改了一下print的内容……

**Comment by sundy-li** [comment]
有点爱莫能助啊, 因为我们这边android跑的很正常..

**Comment by liudanking** [comment]
@sundy-li 请问你android的微信版本是多少？

**Comment by sundy-li** [comment]
最新版本 6.54, 跑的很稳定

**Comment by kangkangv5** [comment]
我的iphone已经能完美运行了，谢谢作者！！！！！！

**Comment by sundy-li** [comment]
@kangkangv5  那我先close这个issues了

**Comment by 7rack** [comment]
android系统都安装了证书，运行报错。
`$ go run examples/custom_output_server.go 
2017/02/17 09:37:43 server will at port:8899

Running a new wechat processor, please wait...
result urls size => 37
Running a new wechat processor, please wait...
2017/02/17 09:54:43 Failed parse main
 --- at github.com/sundy-li/wechat_spider/processor.go:166 (BaseProcessor.processMain) ---
Caused by: MsgLists not found
result urls size => 0
Running a new wechat processor, please wait...
2017/02/17 09:54:45 Failed parse main
 --- at github.com/sundy-li/wechat_spider/processor.go:166 (BaseProcessor.processMain) ---
Caused by: MsgLists not found
result urls size => 0
`
手机上显示请在微信客户端打开。请问还是证书的问题吗？

**Comment by sundy-li** [comment]
@7rack  先更新微信到最新版本吧,

**Comment by 7rack** [comment]
@sundy-li 我通过电脑客户端去尝试，也是同样的情况。最后把_bizs数组改成我需要点击的公众号就没有警告了。但是会一直刷新这个公众号的历史文章。
`
wechat_spider (master)]$ go run examples/custom_output_server.go 
2017/02/17 13:53:14 server will at port:8899
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10
Running a new wechat processor, please wait...
result urls size => 10

`
看来我还是没搞明白Output的执行逻辑，可有更详细点的自定义Output及NextBiz部分

**Comment by liudanking** [comment]
@kangkangv5 你后来是怎么修改成功在iphone上跑起来的？

**Comment by kangkangv5** [comment]
@liudanking 没有任何修改。原装代码。
