### ISSUE TITLE
./file_output_server.go:39: undefined: u

### ISSUE THREAD

**Issue by donglua** [sundy-li/wechat_spider#17]
$ go run file_output_server.go
    # command-line-arguments
    ./file_output_server.go:39: undefined: u

![image](https://cloud.githubusercontent.com/assets/3875265/22766475/9f3ffe2c-eeb0-11e6-9c57-72e156df36f8.png)

**Comment by sundy-li** [comment]
FIXED in commit 0efab57d67c0f659f66ded1175aa4ba55820f639
