### ISSUE TITLE
使用iphone7 plus机型，批量获取失败。会出现两个问题，楼主有时间看下是什么问题

### ISSUE THREAD

**Issue by steven-ji** [sundy-li/wechat_spider#18]
会出现两个：1.第一查看某公众号的历史信息，只能获取当前公众号历史文章，不会触发其他公众号，点击第二次才会；2.批量获取过程中，出现报错，其他公众号的数据获取报错。下面是返回值<p>请在微信客户端打开链接。
document.addEventListener('WeixinJSBridgeReady', function onBridgeReady() {
					var appId = '',
						imgUrl = ''
						link = 'http://mp.weixin.qq.com/mp/conference/default/share',
						title = '失效的验证页面'
						desc = '你暂无权限查看此页面内容。',
						content = '#微信分享#，你暂无权限查看此页面内容。'

**Comment by liudanking** [comment]
iphone 6 plus一样的问题

**Comment by sundy-li** [comment]
抱歉,最近忙现在才看到, 我这边暂时没有iphone 7机器来测试,建议用android,并且添加好证书

 如果必须用iphone的话, 上一个issue的朋友 iphone已经完美运行了,  你们可以联系下 @ kangkangv5

**Comment by kangkangv5** [comment]
抱歉帮不上什么忙，我用iphone，安卓，甚至安卓模拟器，都可以运行。
代码没有改动。

只有windows系统下微信客户端会出现“请在微信客户端打开连接”的问题，其余的可以运行。（要不各位试试模拟器？）

**Comment by 258513813** [comment]
模拟器用哪种？

**Comment by 258513813** [comment]
nextBiz 方法只在handleList 中被调用了一次。 将要抓的微信公众号放在  bizs 数组中每次是随机获取一个biz来抓取，这个方式怎么能批量获取到呢？ 应该是轮询 nextBiz 方法才对吧。

**Comment by 258513813** [comment]
Cannot write TLS response body from mitm'd client: write tcp 127.0.0.1:8899->127.0.0.1:60035: wsasend: An established connection was aborted by the software in your host machine.

另外系统包了这个异常

**Comment by sundy-li** [comment]
@258513813  nextbiz就是实现了一个链路,我那个example是随机取的,只是示范一下, 你可以自己实现这个方法来做,   你那个异常应该是手机取消了打开某个链接导致的
