### ISSUE TITLE
iphome 6s 不支持

### ISSUE THREAD

**Issue by jackwu365** [sundy-li/wechat_spider#2]
如题

**Comment by sundy-li** [comment]
由于iphone端的微信公众号链接是 基于https协议的请求,  这个服务的主要原理是代理中间人攻击, 如果要 hack https中的内容, 需要 proxy代理端 以及 iphone客户端 添加自己生产的cert证书, 目前来说仅仅用来爬取微信公众号支持这个成本过高,   后续将先支持 pc端批量模拟点击爬虫 ,  https这个将会在此之后支持
