### ISSUE TITLE
试用iOS iphone6 会出现

### ISSUE THREAD

**Issue by 258513813** [sundy-li/wechat_spider#21]
WARN: Cannot handshake client mp.weixin.qq.com:443 remote error: tls: unknown certificate authority，
这个证书手机上面怎么安装呢？
另外赞助了，怎么联系您的qq呢？

**Comment by sundy-li** [comment]
感谢支持, 证书在certs文件下, 对应文件发到手机打开就行了,可以具体google下
qq在FAQ文档
