### ISSUE TITLE
希望可以监听tcp4的端口

### ISSUE THREAD

**Issue by yswtrue** [sundy-li/wechat_spider#22]

**Comment by sundy-li** [comment]
请问下 tcp4是什么, 为什么要监听tcp4的端口?    可以解释下吗

**Comment by yswtrue** [comment]
`netstat -nptl
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:8118          0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:17500           0.0.0.0:*               LISTEN      1626/dropbox        
tcp        0      0 0.0.0.0:29917           0.0.0.0:*               LISTEN      2849/wineserver     
tcp        0      0 127.0.0.1:17600         0.0.0.0:*               LISTEN      1626/dropbox        
tcp        0      0 127.0.0.1:17603         0.0.0.0:*               LISTEN      1626/dropbox        
tcp        0      0 0.0.0.0:64292           0.0.0.0:*               LISTEN      8831/electron --typ 
tcp        0      0 127.0.0.1:2376          0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:4300          0.0.0.0:*               LISTEN      2849/wineserver     
tcp        0      0 127.0.0.1:5037          0.0.0.0:*               LISTEN      4708/adb            
tcp        0      0 127.0.0.1:4301          0.0.0.0:*               LISTEN      2849/wineserver     
tcp        0      0 127.0.0.1:8911          0.0.0.0:*               LISTEN      2849/wineserver     
tcp        0      0 0.0.0.0:8593            0.0.0.0:*               LISTEN      2849/wineserver     
tcp6       0      0 :::22                   :::*                    LISTEN      -                   
tcp6       0      0 :::17500                :::*                    LISTEN      1626/dropbox        
tcp6       0      0 :::8899                 :::*                    LISTEN      10138/test          
`
貌似我这里打开时候都是监听的tcp6的协议，然后我设置了代理没有效果

**Comment by sundy-li** [comment]
我这里也是tcp6, 和这个无关, 你看看是不是防火墙问题 telnet ip 端口试下

**Comment by yswtrue** [comment]
好的，谢了

**Comment by yswtrue** [comment]
我那时候设置代理无效是我的手机开了影梭，关了就可以了
