### ISSUE TITLE
nextBiz 获取下一个公众号失败

### ISSUE THREAD

**Issue by 258513813** [sundy-li/wechat_spider#24]
2017/02/28 18:21:03 [248] WARN: Cannot write TLS response body from mitm'd client: write tcp 127.0.0.1:8899->127.0.0.1:50209: wsasend: An established connection was aborted by the software in your host machine.
2017/02/28 18:21:03 [250] WARN: Cannot write TLS response body from mitm'd client: write tcp 127.0.0.1:8899->127.0.0.1:50210: wsasend: An established connection was aborted by the software in your host machine.
2017/02/28 18:21:03 [252] WARN: Cannot write TLS response body from mitm'd client: write tcp 127.0.0.1:8899->127.0.0.1:50211: wsasend: An established connection was aborted by the software in your host machine.

另外就是之前说，捐助之后加qq联系更新，怎么加qq呢？

**Comment by sundy-li** [comment]
自动翻页要设置 AutoScroll参数, qq见FAQ文档

**Comment by 258513813** [comment]
我表达错了，是不能获取下一个biz 的时候失败，报了上面的异常。就是不会nextBizs 方法不会二次调用，在微信打开一个网页之后不会进行二次刷新操作， 写js的方式应该是失败了，报了上面的异常，

**Comment by pandazki** [comment]
似乎是被限制了。。我刚试也是

**Comment by 258513813** [comment]
可以解决吧？，大佬。

**Comment by sundy-li** [comment]
我在android的最新版本微信6.5.4  跑custom_output_server.go 正常

提issue的时候 请告知

1.你运行的代码,你的 操作是什么
2. 你的客户端操作系统, 微信版本, 是否添加成功证书
3.执行的结果是什么

另外请不要发无意义的评论,多谢合作

**Comment by 258513813** [comment]
1、我运行的是custom_out_server.go
2、运行的是安卓模拟器4.4.2（逍遥安卓）,微信6.5.4，证书应该成功添加了，可以打开页面但是nextBiz不会自动刷；
3、执行的结果就是出来我首次打开历史记录的20条结果，我在_bizs 数组里面添加的 biz 都不会继续刷了。

**Comment by 258513813** [comment]
不好意思，应该是我自己重写custom_out_server.go读取文件批量获取的时候有问题，才导致的异常。
``package main

import (
	"bufio"
	"fmt"
	"io"
	//"math/rand"
	"os"

	spider "github.com/sundy-li/wechat_spider"
)

func main() {
	var port = "8899"
	ReadLine("input.txt")
	spider.InitConfig(&spider.Config{
		Verbose:    false, // Open to see detail logs
		AutoScroll: false, // Open to crawl scroll pages
	})
	spider.Regist(&CustomProcessor{})
	spider.Run(port)
}

//Just to implement Output Method of interface{} Processor
type CustomProcessor struct {
	spider.BaseProcessor
}

func (c *CustomProcessor) Output() {
	urls := []string{}
	f, _ := os.OpenFile("result.txt", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0660) //os.O_APPEND 追加新文件 O_CREATE
	for _, r := range c.UrlResults() {
		urls = append(urls, r.Url)
		io.WriteString(f, r.Url)
		f.WriteString("\n")
	}
	fmt.Printf("%#v\n", urls)

	// You can dump the get the html from urls and save to your database
}

// NextBiz hijack the script, set the location to next url after 2 seconds
func (c *CustomProcessor) NextBiz(currentBiz string) string {
	// Random select
	//return _bizs[rand.Intn(len(_bizs))]
	//return _bizs[1]
	//return readLine("input.txt")
	fmt.Println("start next Biz")
	if index < size {
		fmt.Println("index: ", index)
		index = index + 1
		return _bizs[index-1]
	} else {
		fmt.Println("crawl bizs end, the size is:", size)
		return ""
	}
}

func ReadLine(filename string) {
	f, err := os.Open(filename)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	rd := bufio.NewReader(f)
	var i = 0
	for {
		line, err := rd.ReadString('\n')
		_bizs[i] = line
		i = i + 1

		if err != nil || io.EOF == err || i >= 1000 {
			fmt.Println("read bizs file stop the size is: ", i)
			if i >= 1000 {
				fmt.Println("read bizs file stop the size can't more than 1000, now size: ", i)
			}
			break
		} else {
			fmt.Println("i: ", i)
		}
	}
	size = i
	fmt.Println("size: ", size)
}

var (
	//_bizs = []string{"MzIyMTU1NjY4NQ==", "MzA5NDk4ODI4Mw==", "MjM5MjEyOTEyMQ=="}
	_bizs = [10]string{}
	index = 0
	size  = 0
)

**Comment by sundy-li** [comment]
没问题的话, 我先关闭这个issue了
