### ISSUE TITLE
Mac 微信客户端在调用 NextBiz 爬取其他指定公众号时，微信内置浏览器出现「请在微信客户端打开链接。」的错误提示。

### ISSUE THREAD

**Issue by pandazki** [sundy-li/wechat_spider#25]
1. 略微修改 custom_output_server, 指定了2个想要爬取的公众号
	_bizs = []string{"MjM5Njc2NDEwMA==", "MzIwNDA2NjQ4NA=="}

2. Mac 最新版微信客户端，证书已经安装成功

3. 手动点开的公众号可以正常抓取，请求 NextBiz 时在浏览器出现「请在微信客户端打开链接。」的错误提示。

iPhone7 Wechat 客户端可以正常抓取。

**Comment by sundy-li** [comment]
目前 mac客户端 win客户端 还存在bug尚未修复, 请先暂时用android iphone

**Comment by sundy-li** [comment]
Fixed in #28  增加了基于mac,win下的模拟点击代码
