### ISSUE TITLE
爬取后，会增加阅读数吗？或者如何实现阅读量的增加？

### ISSUE THREAD

**Issue by liujia123888** [sundy-li/wechat_spider#26]
提问之前,请务必带有以下信息,不接受非技术性issue

1. 你运行的代码命令,你的操作是什么

2. 你的客户端操作系统, 微信版本, 是否添加成功证书

3. 执行的结果是什么

**Comment by sundy-li** [comment]
爬取的操作和用户点击详情文章一样, 第一次爬取会增加阅读数,后面不会

**Comment by liujia123888** [comment]
微信判断不同用户的参数是什么？

**Comment by liujia123888** [comment]
其实就是想做一个刷公众号文章阅读量的爬虫，给个思路呀？

**Comment by sundy-li** [comment]
放弃吧,这个代码帮不了你的...
