### ISSUE TITLE
import中的一点小问题

### ISSUE THREAD

**Issue by liuzhuzhu** [sundy-li/wechat_spider#29]
您好,我done下您的代码看了下,import 部分的这个地方"github.com/elazarl/goproxy"提示报异常,这个是怎么回事儿?我的编辑器使用的golang idea 缺少这个包,这个包是需要自己去引入吗?

**Comment by sundy-li** [comment]
命令行:  go get github.com/elazarl/goproxy 

请先百度google一下  如何安装go三方包, 不要受ide局限
