### ISSUE TITLE
是否需要关注所有待抓取的公众号？

### ISSUE THREAD

**Issue by Y-owen** [sundy-li/wechat_spider#3]
您好，是否需要关注所有待抓取的公众号？现在的key是跟公众号相对应起来了吧？

**Comment by sundy-li** [comment]
因为是中间人攻击,完全是拦截客户端操作, 所以无关key,  win客户端只需要拿到__biz参数即可(微信公众号唯一,可以通过很多方法获取, 比如从某一篇文章链接)

抓取的是历史页面所有文章, 如果没有关注 历史文章页面只显示有限文章(10条貌似), 适合增量爬取
如果有关注,可以自动化爬取所有链接,适合一次性爬取
