### ISSUE TITLE
小号robot连续运行一个小时后疑似被封，返回“页面无法打开”

### ISSUE THREAD

**Issue by tomzhu6066** [sundy-li/wechat_spider#35]
windows桌面微信，已添加证书。
由服务器端给需要更新key的历史页地址列表，robot输入地址后拦截新地址。
基本一秒一个运行了1小时后，内部浏览器内打开任何历史页地址都是“页面无法打开”，但是打开单个文章页可以，打开百度可以，加好友可以，其他功能基本没问题。
想问一下，由于是新注册微信号，是不是触发了访问限制？用老号是不是会好？频次大概多少不会被封呢？

**Comment by sundy-li** [comment]
是的, 新号容易被封,  腾讯用户行为决定封不封你的号
