### ISSUE TITLE
安卓连本机代理无反应

### ISSUE THREAD

**Issue by hyhero127** [sundy-li/wechat_spider#7]
用的是simple_server.go

**Comment by sundy-li** [comment]
1. 要点击 查看历史文章按钮 才触发
2. 确保android设置代理后可以访问网络

**Comment by sundy-li** [comment]
我这里试了很多机型 都是可以的, 微信版本  最新  6.3.31

**Comment by huangbaoquan** [comment]
微信版本：6.3.28
微信能连上代理访问网络
也点击了公众号的“查看历史消息”
报一下错误： 
WARN: Error copying to client: read tcp 192.168.23.10:64853->23.72.237.108:443: read tcp 192.168.23.10:8899->192.168.23.14:33216: read: connection reset by peer
