### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by fifyrio** [sundy-li/wechat_spider#8]
wuwdeMac-mini:goWorkplace wuw$ go run spider.go
spider.go:7:2: cannot find package "github.com/elazarl/goproxy" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/github.com/elazarl/goproxy (from $GOROOT)
	/Users/wuw/Documents/goWorkspace/src/github.com/elazarl/goproxy (from $GOPATH)

**Comment by sundy-li** [comment]
go get -u github.com/elazarl/goproxy 下载第三方包

cannot find package XX, 都用go get -u命令下载
